
create proc [dbo].[spUpdateTCCallDetailFromAPI]
@dtCallDetails TCCallDetailFromAPI readonly
as
begin

insert into tblTCCallDetailFromAPI([AgentID]
      ,[AgentName]
      ,[AgentPhoneNumber]
      ,[AgentStatus]
      ,[AgentUniqueID]
      ,[Apikey]
      ,[AudioFile]
      ,[CallDuration]
      ,[CallerConfAudioFile]
      ,[CallerID]
      ,[CampaignName]
      ,[CampaignStatus]
      ,[Comments]
      ,[ConfDuration]
      ,[CustomerStatus]
      ,[DataUniqueId]
      ,[DialStatus]
      ,[DialedNumber]
      ,[DID]
      ,[Disposition]
      ,[Duration]
      ,[EndTime]
      ,[FallBackRule]
      ,[HangupBy]
      ,[Location]
      ,[monitorUCID]
      ,[PhoneName]
      ,[Skill]
      ,[StartTime]
      ,[Status]
      ,[TimeToAnswer]
      ,[TransferredTo]
      ,[TransferType]
      ,[Type]
      ,[UserName]
      ,[UUI]
      ,[WrapUpDuration]
	  ,[TimeStampIns])

SELECT  [AgentID]
      ,[AgentName]
      ,[AgentPhoneNumber]
      ,[AgentStatus]
      ,[AgentUniqueID]
      ,[Apikey]
      ,[AudioFile]
      ,[CallDuration]
      ,[CallerConfAudioFile]
      ,[CallerID]
      ,[CampaignName]
      ,[CampaignStatus]
      ,[Comments]
      ,[ConfDuration]
      ,[CustomerStatus]
      ,[DataUniqueId]
      ,[DialStatus]
      ,[DialedNumber]
      ,[DID]
      ,[Disposition]
      ,[Duration]
      ,[EndTime]
      ,[FallBackRule]
      ,[HangupBy]
      ,[Location]
      ,[monitorUCID]
      ,[PhoneName]
      ,[Skill]
      ,[StartTime]
      ,[Status]
      ,[TimeToAnswer]
      ,[TransferredTo]
      ,[TransferType]
      ,[Type]
      ,[UserName]
      ,[UUI]
      ,[WrapUpDuration], GETDATE()
FROM            @dtCallDetails

end