CREATE TYPE [dbo].[DebitNoteTypeDetail] AS TABLE (
    [DebNoteTypeId]             TINYINT        NULL,
    [InvPurchDetailId]          INT            NULL,
    [InvPurchaseId]             INT            NULL,
    [StkMovDetId]               INT            NULL,
    [StkMovId]                  INT            NULL,
    [DamageExpirySKUClaimDetId] INT            NULL,
    [DamageExpirySKUClaimId]    INT            NULL,
    [OrderReturnDetailId]       INT            NULL,
    [OrderReturnStepsId]        INT            NULL,
    [OrderReturnResolutionId]   INT            NULL,
    [PrdId]                     INT            NULL,
    [Prdbatchid]                INT            NULL,
    [StockStatusId]             TINYINT        NULL,
    [Qty]                       INT            NULL,
    [Rate]                      [dbo].[Amount] NULL,
    [RateBeforeTax]             [dbo].[Amount] NULL,
    [ValueBeforeTax]            [dbo].[Amount] NULL,
    [DiscAmt]                   [dbo].[Amount] NULL,
    [ValueBeforeTaxAfterDisc]   [dbo].[Amount] NULL,
    [Tax]                       [dbo].[Amount] NULL,
    [TaxValue]                  [dbo].[Amount] NULL,
    [ValueAfterTax]             [dbo].[Amount] NULL,
    [Percentage]                [dbo].[Amount] NULL,
    [ClaimAmount]               [dbo].[Amount] NULL,
    [IsInclude]                 BIT            NULL);

