CREATE TYPE [dbo].[udt_RawDataInvoiceDetail] AS TABLE (
    [InvoiceNumber]          NVARCHAR (500) NULL,
    [TmpInvoiceCodePDA]      NVARCHAR (500) NULL,
    [StoreID]                NVARCHAR (500) NULL,
    [CatID]                  NVARCHAR (500) NULL,
    [ProdID]                 NVARCHAR (500) NULL,
    [ProductPrice]           NVARCHAR (500) NULL,
    [TaxRate]                NVARCHAR (500) NULL,
    [flgRuleTaxVal]          NVARCHAR (500) NULL,
    [OrderQty]               NVARCHAR (500) NULL,
    [UOMId]                  NVARCHAR (500) NULL,
    [LineValBfrTxAftrDscnt]  NVARCHAR (500) NULL,
    [LineValAftrTxAftrDscnt] NVARCHAR (500) NULL,
    [FreeQty]                NVARCHAR (500) NULL,
    [DisVal]                 NVARCHAR (500) NULL,
    [SampleQuantity]         NVARCHAR (500) NULL,
    [ProductShortName]       NVARCHAR (500) NULL,
    [TaxValue]               NVARCHAR (500) NULL,
    [OrderIDPDA]             NVARCHAR (500) NULL,
    [flgIsQuoteRateApplied]  NVARCHAR (500) NULL,
    [ServingDBRId]           NVARCHAR (500) NULL,
    [flgWholeSellApplicable] NVARCHAR (500) NULL,
    [ProductExtraOrder]      NVARCHAR (500) NULL,
    [flgDrctslsIndrctSls]    NVARCHAR (500) NULL,
    [SuggestedQty]           NVARCHAR (500) NULL,
    [Discperpcs]             NVARCHAR (500) NULL,
    [flgInCarton]            NVARCHAR (500) NULL);

