CREATE TYPE [dbo].[udt_RawDataPersonRegDetails] AS TABLE (
    [IMEI]              NVARCHAR (500) NULL,
    [ClickedDateTime]   NVARCHAR (500) NULL,
    [Name]              NVARCHAR (500) NULL,
    [ContactNo]         NVARCHAR (500) NULL,
    [DOB]               NVARCHAR (500) NULL,
    [Sex]               NVARCHAR (500) NULL,
    [MaritalStatus]     NVARCHAR (500) NULL,
    [MarriedDate]       NVARCHAR (500) NULL,
    [Qualification]     NVARCHAR (500) NULL,
    [SelfieName]        NVARCHAR (500) NULL,
    [SelfiePath]        NVARCHAR (500) NULL,
    [EmailID]           NVARCHAR (500) NULL,
    [BloodGroup]        NVARCHAR (500) NULL,
    [SignName]          NVARCHAR (500) NULL,
    [SignPath]          NVARCHAR (500) NULL,
    [Sstat]             NVARCHAR (500) NULL,
    [PhotoName]         NVARCHAR (500) NULL,
    [PersonNodeId]      NVARCHAR (500) NULL,
    [PersonNodeType]    NVARCHAR (500) NULL,
    [BankAccountnumber] NVARCHAR (500) NULL,
    [BankID]            NVARCHAR (500) NULL,
    [IFSCCode]          NVARCHAR (500) NULL,
    [flgUPIID]          NVARCHAR (500) NULL,
    [UPIID]             NVARCHAR (500) NULL,
    [AadhaarNumber]     NVARCHAR (500) NULL);

