CREATE TABLE [dbo].[OutletMasterLoad] (
    [UserErpID]       NVARCHAR (255)   NULL,
    [User ]           NVARCHAR (255)   NULL,
    [Outlet Erp Id]   NVARCHAR (255)   NULL,
    [Outlets Name]    NVARCHAR (255)   NULL,
    [Route Name]      NVARCHAR (255)   NULL,
    [Beats Name]      NVARCHAR (255)   NULL,
    [Beats Erp id]    NVARCHAR (255)   NULL,
    [Route ErpId]     NVARCHAR (255)   NULL,
    [StoreID]         INT              NULL,
    [RouteNodeID]     INT              NULL,
    [CovNodeID]       INT              NULL,
    [LatCode]         NUMERIC (27, 22) NULL,
    [LongCode]        NUMERIC (27, 22) NULL,
    [SSErpID]         NVARCHAR (255)   NULL,
    [SSName]          NVARCHAR (255)   NULL,
    [DistributorCode] NVARCHAR (255)   NULL,
    [Distributor]     NVARCHAR (255)   NULL,
    [Type]            NVARCHAR (255)   NULL,
    [DHNodeID]        INT              NULL,
    [DHNodeType]      SMALLINT         NULL,
    [State]           NVARCHAR (255)   NULL,
    [StateID]         INT              NULL
);

