CREATE TABLE [dbo].[RajSFAHierarchy] (
    [DSRAreaID]              FLOAT (53)     NULL,
    [RSMArea]                NVARCHAR (255) NULL,
    [Aria]                   NVARCHAR (255) NULL,
    [RSM EmpCode]            NVARCHAR (255) NULL,
    [RSMPersonName]          NVARCHAR (255) NULL,
    [StateHeadArea]          NVARCHAR (255) NULL,
    [StateHead EmpCode]      NVARCHAR (255) NULL,
    [StateHeadPersonName]    NVARCHAR (255) NULL,
    [ASMArea]                NVARCHAR (255) NULL,
    [Aria1]                  NVARCHAR (255) NULL,
    [ASMEmpCode]             NVARCHAR (255) NULL,
    [ASMPersonName]          NVARCHAR (255) NULL,
    [SOArea]                 NVARCHAR (255) NULL,
    [SOEmpCode]              NVARCHAR (255) NULL,
    [SOPersonName]           NVARCHAR (255) NULL,
    [Status]                 NVARCHAR (255) NULL,
    [DSRArea]                NVARCHAR (255) NULL,
    [DSREmpCode]             NVARCHAR (255) NULL,
    [DSRPersonName]          NVARCHAR (255) NULL,
    [OLDSOAreaID]            INT            NULL,
    [OLDASMAreaID]           INT            NULL,
    [OLDRSMAreaID]           INT            NULL,
    [OLDStateHeadAreaID]     INT            NULL,
    [OLDStateHeadID]         INT            NULL,
    [OLDRSMID]               INT            NULL,
    [OLDSOID]                INT            NULL,
    [OLDASMID]               INT            NULL,
    [NEWSOAreaID]            INT            NULL,
    [NEWASMAreaID]           INT            NULL,
    [NEWRSMAreaID]           INT            NULL,
    [NEWStateHeadAreaID]     INT            NULL,
    [NEWStateHeadID]         INT            NULL,
    [NEWRSMID]               INT            NULL,
    [NEWSOID]                INT            NULL,
    [NEWASMID]               INT            NULL,
    [OLDDSRAreaID]           INT            NULL,
    [OLDDSRID]               INT            NULL,
    [NEWDSRAreaID]           INT            NULL,
    [NEWDSRID]               INT            NULL,
    [NEWRSMAreaHierID]       INT            NULL,
    [NEWStateHeadAreaHierID] INT            NULL,
    [NewASMAreaHierID]       INT            NULL,
    [NEWSOAreaHierID]        INT            NULL,
    [NewDSRAreaHierID]       INT            NULL
);

