CREATE TABLE [dbo].[tblInvMaster] (
    [InvID]               INT             IDENTITY (1, 1) NOT NULL,
    [InvCode]             VARCHAR (50)    NULL,
    [InvInitTag]          VARCHAR (3)     NULL,
    [InvSeqNo]            INT             NULL,
    [InvDate]             DATE            NULL,
    [StoreID]             INT             NULL,
    [NetRoundedAmount]    AS              (round([NetInvoiceValue],(0))),
    [NetInvoiceValue]     [dbo].[Amount]  NULL,
    [TotalTaxAmount]      NUMERIC (18, 2) NULL,
    [TotalInvoiceValue]   NUMERIC (18, 2) NULL,
    [TotalDiscountAmount] NUMERIC (18, 2) NULL,
    [TotInvoiceValWDisc]  NUMERIC (18, 2) NULL,
    [TotLineOrderVal]     NUMERIC (18, 2) NULL,
    [TotLineLevelDisc]    NUMERIC (18, 2) NULL,
    [InvType]             TINYINT         NULL,
    [flgInvStatus]        TINYINT         NULL,
    [flgCollectCash]      TINYINT         NULL,
    [Remarks]             VARCHAR (100)   NULL,
    [DBRNodeId]           INT             NULL,
    [DBRNodeType]         INT             NULL,
    [LoginIDIns]          INT             CONSTRAINT [DF_tblInvMaster_LoginIDIns] DEFAULT ((0)) NULL,
    [TimestampIns]        DATETIME        CONSTRAINT [DF_tblInvMaster_TimestampIns] DEFAULT (getdate()) NULL,
    [LoginIDUpd]          INT             NULL,
    [TimestampUpd]        DATETIME        NULL,
    [FYID]                INT             NULL,
    [InvCreatedOn]        DATE            NULL,
    [PckLstId]            INT             NULL,
    [InvActDiscAmt]       [dbo].[Amount]  NULL,
    [OrderId]             INT             NULL,
    [flgInvoicePrinted]   TINYINT         CONSTRAINT [DF_tblInvMaster_flgInvoicePrinted] DEFAULT ((0)) NULL,
    [strSchemeBenefit]    VARCHAR (MAX)   NULL,
    [ReasonId]            INT             NULL,
    [ReasonText]          VARCHAR (500)   NULL,
    [OldInvId]            INT             NULL,
    [InvCreatedFrom]      TINYINT         CONSTRAINT [DF_tblInvMaster_InvCreatedFrom] DEFAULT ((1)) NOT NULL,
    [TotOtherCharges]     [dbo].[Amount]  DEFAULT ((0)) NOT NULL,
    [VanNodeID]           INT             NULL,
    [VanNodeType]         SMALLINT        NULL,
    [CustomerNodeId]      INT             NULL,
    [CustomerNodeType]    INT             NULL,
    [flgRegenerate]       TINYINT         NULL,
    CONSTRAINT [PK_tblInvMaster] PRIMARY KEY CLUSTERED ([InvID] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'1:Order Process,2:PickList Adjustment,3:Post Delivery', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblInvMaster', @level2type = N'COLUMN', @level2name = N'InvCreatedFrom';

