CREATE TABLE [dbo].[tblJointVisitMaster_ASM] (
    [JointVisitId]                          INT              IDENTITY (1, 1) NOT NULL,
    [JointVisitCode]                        VARCHAR (100)    NULL,
    [ManagerNodeId]                         INT              NOT NULL,
    [ManagerNodeType]                       SMALLINT         NOT NULL,
    [CoverageID]                            INT              NOT NULL,
    [CoverageNodeType]                      SMALLINT         NOT NULL,
    [VisitDate]                             DATE             NOT NULL,
    [ActualLatitude]                        DECIMAL (27, 24) NULL,
    [ActualLongitude]                       DECIMAL (27, 24) NULL,
    [VisitStartDateTime]                    DATETIME         NULL,
    [VisitEndDatetime]                      DATETIME         NULL,
    [MapAddress]                            VARCHAR (500)    NULL,
    [MapPinCode]                            VARCHAR (50)     NULL,
    [MapCity]                               VARCHAR (100)    NULL,
    [MapState]                              VARCHAR (100)    NULL,
    [LocationProvider]                      VARCHAR (200)    NOT NULL,
    [Accuracy]                              VARCHAR (200)    NOT NULL,
    [IMEINo]                                VARCHAR (50)     NULL,
    [TIMESTAMP]                             DATETIME         CONSTRAINT [DF_tblJointVisitMaster_ASM_TIMESTAMP] DEFAULT (getdate()) NOT NULL,
    [AllProviderData]                       VARCHAR (500)    NULL,
    [GPSLatitude]                           NUMERIC (18, 16) NULL,
    [GPSLongitude]                          NUMERIC (18, 16) NULL,
    [GPSAccuracy]                           VARCHAR (100)    NULL,
    [GPSAddress]                            VARCHAR (500)    NULL,
    [NetworkLatitude]                       NUMERIC (18, 16) NULL,
    [NetworkLongitude]                      NUMERIC (18, 16) NULL,
    [NetworkAccuracy]                       VARCHAR (100)    NULL,
    [NetworkAddress]                        VARCHAR (500)    NULL,
    [FusedLatitude]                         NUMERIC (18, 16) NULL,
    [FusedLongitude]                        NUMERIC (18, 16) NULL,
    [FusedAccuracy]                         VARCHAR (100)    NULL,
    [FusedAddress]                          VARCHAR (500)    NULL,
    [flgLocationServicesOnOff]              TINYINT          NULL,
    [flgGPSOnOff]                           TINYINT          NULL,
    [flgNetworkOnOff]                       TINYINT          NULL,
    [flgFusedOnOff]                         TINYINT          NULL,
    [flgInternetOnOffWhileLocationTracking] TINYINT          NULL,
    [flgRestart]                            TINYINT          NULL,
    [Address]                               VARCHAR (500)    NULL,
    CONSTRAINT [PK_tblJointVisitMaster_ASM] PRIMARY KEY CLUSTERED ([JointVisitId] ASC)
);

