CREATE TABLE [dbo].[tblOutGoingMsgDetails] (
    [ID]               INT             IDENTITY (1, 1) NOT NULL,
    [SMSTo]            VARCHAR (250)   NULL,
    [SMSFrom]          VARCHAR (250)   NULL,
    [Msg]              NVARCHAR (4000) NULL,
    [SendTime]         DATETIME        NULL,
    [DateTimeStamp]    DATETIME        CONSTRAINT [DF_tblOutGoingMsgDetails_DateTimeStamp_1] DEFAULT (getdate()) NULL,
    [FlgStatus]        TINYINT         CONSTRAINT [DF_tblOutGoingMsgDetails_FlgStatus_1] DEFAULT ((0)) NULL,
    [RecieverName]     VARCHAR (500)   NULL,
    [FailureMsg]       VARCHAR (3000)  NULL,
    [IsRecdPicked]     INT             CONSTRAINT [DF_tblOutGoingMsgDetails_IsRecdPicked_1] DEFAULT ((0)) NULL,
    [AppType]          INT             NULL,
    [MessageID]        VARCHAR (200)   NULL,
    [ServiceProvider]  VARCHAR (200)   NULL,
    [DeliveryStatus]   VARCHAR (200)   NULL,
    [DeliveryDateTime] DATETIME        NULL,
    [ServiceName]      VARCHAR (200)   NULL,
    [SourceRefId]      INT             NULL,
    [SourceTypeId]     INT             NULL,
    [NoOfCredit]       INT             NULL,
    [strDelivery]      VARCHAR (2000)  NULL,
    [NodeId]           INT             NULL,
    [NodeType]         INT             NULL,
    [SenderId]         VARCHAR (6)     NULL,
    [flgUniCode]       TINYINT         CONSTRAINT [DF__tblOutGoi__flgUn__2A61254E] DEFAULT ((0)) NOT NULL,
    [flgProcessed]     BIT             CONSTRAINT [DF_tblOutGoingMsgDetails_flgProcessed] DEFAULT ((0)) NOT NULL,
    [TeleUserId]       INT             NOT NULL,
    [RuleId]           TINYINT         NOT NULL,
    [SMSTypeId]        TINYINT         NULL,
    CONSTRAINT [PK_tblOutGoingMsgDetails] PRIMARY KEY CLUSTERED ([ID] ASC)
);

