CREATE TABLE [dbo].[tblOLAPFullSalesHierarchy] (
    [RegionID]             INT           NULL,
    [RegionNodeType]       INT           NULL,
    [RegionHierID]         VARCHAR (50)  NULL,
    [Region]               VARCHAR (200) NULL,
    [ZoneID]               INT           NULL,
    [ZoneNodeType]         INT           NULL,
    [ZoneHierID]           VARCHAR (50)  NULL,
    [Zone]                 VARCHAR (200) NULL,
    [ASMAreaID]            INT           NOT NULL,
    [ASMAreaNodeType]      INT           NULL,
    [ASMAreaHierID]        VARCHAR (50)  NOT NULL,
    [ASMArea]              VARCHAR (200) NULL,
    [SOAreaID]             INT           NOT NULL,
    [SOAreaNodeType]       INT           NULL,
    [SOAreaHierID]         VARCHAR (50)  NOT NULL,
    [SOArea]               VARCHAR (200) NULL,
    [DBRNodeID]            INT           NOT NULL,
    [DBRNodeType]          INT           NULL,
    [DBRHierID]            VARCHAR (50)  NOT NULL,
    [DBRCode]              VARCHAR (50)  NULL,
    [DBR]                  VARCHAR (200) NULL,
    [CoverageAreaID]       INT           NOT NULL,
    [CoverageAreaNodeType] INT           NULL,
    [CoverageAreaHierID]   VARCHAR (50)  NOT NULL,
    [CoverageArea]         VARCHAR (200) NULL,
    [RouteNodeId]          INT           NULL,
    [RouteNodeType]        INT           NULL,
    [RouteHierId]          VARCHAR (50)  NULL,
    [Route]                VARCHAR (200) NULL,
    [StoreID]              INT           NOT NULL,
    [StoreHierId]          VARCHAR (50)  NOT NULL,
    [StoreCode]            VARCHAR (50)  NULL,
    [StoreName]            VARCHAR (500) NULL,
    [flgForTeleCaller]     TINYINT       DEFAULT ((0)) NOT NULL,
    [StarOutlet]           VARCHAR (5)   NULL
);

