CREATE TABLE [dbo].[tblPDASyncStoreMappingMstr] (
    [StoreIDDB]                             INT              IDENTITY (1, 1) NOT NULL,
    [RouteID]                               NVARCHAR (50)    NULL,
    [RouteNodeType]                         SMALLINT         NULL,
    [StoreID]                               NVARCHAR (100)   NULL,
    [OutletName]                            NVARCHAR (200)   NULL,
    [ActualLatitude]                        DECIMAL (30, 27) NULL,
    [ActualLongitude]                       DECIMAL (30, 27) NULL,
    [LocProvider]                           VARCHAR (50)     NULL,
    [Accuracy]                              VARCHAR (100)    NULL,
    [VisitStartTS]                          DATETIME         NULL,
    [VisitEndTS]                            DATETIME         NULL,
    [Imei]                                  VARCHAR (100)    NULL,
    [XMLFullDate]                           VARCHAR (100)    NULL,
    [XMLReceiveDate]                        DATETIME         NULL,
    [BatteryStatus]                         VARCHAR (10)     NULL,
    [OutStat]                               INT              NULL,
    [CreateDate]                            DATETIME         NULL,
    [ModifyDate]                            DATETIME         NULL,
    [AppVersion]                            INT              NULL,
    [FlgActive]                             TINYINT          CONSTRAINT [DF_tblPDASyncStoreMappingMstr_FlgActive] DEFAULT ((1)) NULL,
    [RecordUpdated]                         INT              NULL,
    [OrgStoreId]                            INT              NULL,
    [DistributorID]                         INT              NULL,
    [DistributorType]                       SMALLINT         NULL,
    [flgStoreValidated]                     TINYINT          CONSTRAINT [DF_tblPDASyncStoreMappingMstr_flgStoreValidated] DEFAULT ((0)) NULL,
    [StoreMapAddress]                       VARCHAR (2000)   NULL,
    [City]                                  VARCHAR (200)    NULL,
    [PinCode]                               BIGINT           NULL,
    [State]                                 VARCHAR (200)    NULL,
    [LoginID]                               INT              NULL,
    [PersonId]                              INT              NULL,
    [PersonType]                            INT              NULL,
    [flgToShowInDuplicate]                  TINYINT          CONSTRAINT [DF_tblPDASyncStoreMappingMstr_flgToShowInDuplicate] DEFAULT ((0)) NULL,
    [Address]                               VARCHAR (500)    NULL,
    [Distance]                              NUMERIC (38, 6)  NULL,
    [AllProviderData]                       VARCHAR (500)    NULL,
    [GPSLatitude]                           NUMERIC (18, 16) NULL,
    [GPSLongitude]                          NUMERIC (18, 16) NULL,
    [GPSAccuracy]                           VARCHAR (100)    NULL,
    [GPSAddress]                            VARCHAR (500)    NULL,
    [NetworkLatitude]                       NUMERIC (18, 16) NULL,
    [NetworkLongitude]                      NUMERIC (18, 16) NULL,
    [NetworkAccuracy]                       VARCHAR (100)    NULL,
    [NetworkAddress]                        VARCHAR (500)    NULL,
    [FusedLatitude]                         NUMERIC (18, 16) NULL,
    [FusedLongitude]                        NUMERIC (18, 16) NULL,
    [FusedAccuracy]                         VARCHAR (100)    NULL,
    [FusedAddress]                          VARCHAR (500)    NULL,
    [flgLocationServicesOnOff]              TINYINT          NULL,
    [flgGPSOnOff]                           TINYINT          NULL,
    [flgNetworkOnOff]                       TINYINT          NULL,
    [flgFusedOnOff]                         TINYINT          NULL,
    [flgInternetOnOffWhileLocationTracking] TINYINT          NULL,
    [flgRestart]                            TINYINT          NULL,
    [CityID]                                INT              NULL,
    [StateID]                               INT              NULL,
    [VanNodeID]                             INT              NULL,
    [VanNodeType]                           SMALLINT         NULL,
    [FileSetID]                             INT              NULL,
    CONSTRAINT [PK_tblPDASyncStoreMappingMstr] PRIMARY KEY CLUSTERED ([StoreIDDB] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'0:Yes, 1:No', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblPDASyncStoreMappingMstr', @level2type = N'COLUMN', @level2name = N'flgToShowInDuplicate';

