CREATE TABLE [dbo].[tblRptBeatProfileData] (
    [PersonNodeID]            INT             NULL,
    [AreaNodeId]              INT             NULL,
    [AreaNodeType]            INT             NULL,
    [AreaName]                VARCHAR (200)   NULL,
    [Personname]              VARCHAR (100)   NULL,
    [VisitFrequency]          VARCHAR (100)   NULL,
    [LastVisited]             DATE            NULL,
    [StoreId]                 INT             NULL,
    [IsPlanned]               TINYINT         CONSTRAINT [DF_tblRptBeatProfileData_IsPlanned] DEFAULT ((0)) NULL,
    [IsCovered]               TINYINT         CONSTRAINT [DF_tblRptBeatProfileData_IsCovered] DEFAULT ((0)) NULL,
    [Covered_P4W]             TINYINT         NULL,
    [NotCovered_P4W]          TINYINT         NULL,
    [IsProductive]            TINYINT         CONSTRAINT [DF_tblRptBeatProfileData_IsProductive] DEFAULT ((0)) NULL,
    [Productive_P4W]          TINYINT         NULL,
    [NonProductive_P4W]       TINYINT         NULL,
    [Productive_P3M]          TINYINT         CONSTRAINT [DF_tblRptBeatProfileData_Productive_P3M] DEFAULT ((0)) NULL,
    [NonProductive_P3M]       TINYINT         CONSTRAINT [DF_tblRptBeatProfileData_NonProductive_P3M] DEFAULT ((0)) NULL,
    [NotCoveredInPast2Visits] TINYINT         CONSTRAINT [DF_tblRptBeatProfileData_NotCoveredInPast2Visits] DEFAULT ((0)) NULL,
    [RptMonthYear]            INT             NULL,
    [TimeStampIns]            DATETIME        CONSTRAINT [DF_tblRptBeatProfileData_TimeStampIns] DEFAULT (getdate()) NULL,
    [SalesmanSalesTarget]     NUMERIC (10, 4) NULL,
    [SalesmanSalesAch]        NUMERIC (10, 4) NULL,
    [MTDSales]                NUMERIC (10, 4) NULL,
    [NoOfVisits_MTD]          INT             CONSTRAINT [DF__tblRptBea__NoOfV__3DB3F0E4] DEFAULT ((0)) NOT NULL,
    [NoOfProdVisits_MTD]      INT             CONSTRAINT [DF__tblRptBea__NoOfP__3EA8151D] DEFAULT ((0)) NOT NULL,
    [IsVisitedOnLastVisit]    TINYINT         CONSTRAINT [DF_tblRptBeatProfileData_IsVisitedOnLastVisit] DEFAULT ((0)) NULL,
    [IsProductiveOnLastVisit] TINYINT         CONSTRAINT [DF_tblRptBeatProfileData_IsProductiveOnLastVisit] DEFAULT ((0)) NULL,
    [SaleOnLastVisit]         NUMERIC (10, 4) NULL,
    [flgStarOutlets]          TINYINT         NULL,
    [SalesQty]                BIGINT          NULL
);

