CREATE TABLE [dbo].[tblSFACustomerSupVisit] (
    [StoreCheckVisitID]                     INT              IDENTITY (1, 1) NOT NULL,
    [StoreID]                               INT              NOT NULL,
    [StoreVisitCode]                        VARCHAR (100)    NOT NULL,
    [JointVisitID]                          INT              NULL,
    [flgJointVisit]                         TINYINT          NULL,
    [VisitLatitude]                         DECIMAL (27, 24) NULL,
    [VisitLongitude]                        DECIMAL (27, 24) NULL,
    [VisitDate]                             DATE             NULL,
    [VisitPersonNodeID]                     INT              NULL,
    [VisitPersonNodetype]                   SMALLINT         NULL,
    [DeviceVisitStartTS]                    TIME (7)         NULL,
    [DeviceVisitEndTS]                      TIME (7)         NULL,
    [flgOutletClose]                        TINYINT          NULL,
    [BatteryLeftStatus]                     INT              NOT NULL,
    [LocationProvider]                      VARCHAR (200)    NOT NULL,
    [Accuracy]                              VARCHAR (200)    NOT NULL,
    [TIMESTAMP]                             DATETIME         CONSTRAINT [DF_tblSFACustomerSupVisit_TIMESTAMP] DEFAULT (getdate()) NOT NULL,
    [AllProviderData]                       VARCHAR (500)    NULL,
    [GPSLatitude]                           NUMERIC (18, 16) NULL,
    [GPSLongitude]                          NUMERIC (18, 16) NULL,
    [GPSAccuracy]                           VARCHAR (100)    NULL,
    [GPSAddress]                            VARCHAR (500)    NULL,
    [NetworkLatitude]                       NUMERIC (18, 16) NULL,
    [NetworkLongitude]                      NUMERIC (18, 16) NULL,
    [NetworkAccuracy]                       VARCHAR (100)    NULL,
    [NetworkAddress]                        VARCHAR (500)    NULL,
    [FusedLatitude]                         NUMERIC (18, 16) NULL,
    [FusedLongitude]                        NUMERIC (18, 16) NULL,
    [FusedAccuracy]                         VARCHAR (100)    NULL,
    [FusedAddress]                          VARCHAR (500)    NULL,
    [flgLocationServicesOnOff]              TINYINT          NULL,
    [flgGPSOnOff]                           TINYINT          NULL,
    [flgNetworkOnOff]                       TINYINT          NULL,
    [flgFusedOnOff]                         TINYINT          NULL,
    [flgInternetOnOffWhileLocationTracking] TINYINT          NULL,
    [flgRestart]                            TINYINT          NULL,
    [Address]                               VARCHAR (500)    NULL,
    [Distance]                              NUMERIC (38, 6)  NULL,
    CONSTRAINT [PK_tblSFACustomerSupVisit] PRIMARY KEY CLUSTERED ([StoreCheckVisitID] ASC)
);

