CREATE TABLE [dbo].[tblTeleCallerListForDay_History] (
    [TeleCallingId]                  INT             NOT NULL,
    [AttendDetId]                    INT             NOT NULL,
    [StoreId]                        INT             NOT NULL,
    [Date]                           DATE            NOT NULL,
    [CallMade]                       DATETIME        NULL,
    [DSENodeId]                      INT             NOT NULL,
    [DSENodeType]                    INT             NOT NULL,
    [BranchSubdNodeId]               INT             NOT NULL,
    [BranchSubdNodeType]             INT             NOT NULL,
    [StoreCode]                      VARCHAR (50)    NULL,
    [StoreName]                      VARCHAR (500)   NULL,
    [ContactPerson]                  VARCHAR (100)   NULL,
    [ContactNo]                      VARCHAR (100)   NULL,
    [Channel]                        VARCHAR (100)   NULL,
    [SectorId]                       INT             NOT NULL,
    [flgCallStatus]                  TINYINT         NOT NULL,
    [ScheduleCall]                   VARCHAR (50)    NULL,
    [ReasonId]                       INT             NULL,
    [CallAttempt]                    TINYINT         NULL,
    [TeleReasonId]                   INT             NOT NULL,
    [TeleUserId]                     INT             NOT NULL,
    [Priority]                       SMALLINT        NULL,
    [TotalSales]                     NUMERIC (18, 2) NULL,
    [NoOfInv]                        INT             NULL,
    [LastCallDate]                   DATETIME        NULL,
    [IsFinalDownloadSubmit]          BIT             NOT NULL,
    [IsDownloaded]                   BIT             NOT NULL,
    [OutStandingAmt]                 NUMERIC (18)    NULL,
    [OutStandingDate]                DATE            NULL,
    [InvNo]                          VARCHAR (50)    NULL,
    [InvDate]                        DATE            NULL,
    [LoginIdUpd]                     INT             NULL,
    [TimeSTampUpd]                   DATETIME        NULL,
    [OldTeleCallingId]               INT             NULL,
    [TimeStampIns]                   DATETIME        NOT NULL,
    [TCRouteCalendarId]              INT             NULL,
    [TCPlanCallsMapId]               INT             NULL,
    [LoginIdIns]                     INT             NULL,
    [ChannelId]                      INT             NULL,
    [RuleId]                         INT             NULL,
    [ScheduleDate]                   DATE            NULL,
    [CallStartDate]                  DATETIME        NULL,
    [Remarks]                        VARCHAR (500)   NULL,
    [LastOrderDate]                  DATE            NULL,
    [LastOrderValue]                 NUMERIC (18, 2) NULL,
    [OrderBy]                        VARCHAR (100)   NULL,
    [LastVisit]                      DATE            NULL,
    [LastVisitStatus]                VARCHAR (250)   NULL,
    [VisitedBy]                      VARCHAR (100)   NULL,
    [LastCall]                       DATE            NULL,
    [LastCallStatus]                 VARCHAR (250)   NULL,
    [LastCalledBY]                   VARCHAR (100)   NULL,
    [SubChannelId]                   INT             NULL,
    [SubChannel]                     VARCHAR (150)   NULL,
    [FrequencyId]                    TINYINT         NULL,
    [AlternateContactNo]             VARCHAR (50)    NULL,
    [RouteName]                      VARCHAR (100)   NULL,
    [FiveStarRuleId]                 TINYINT         NULL,
    [FiveStarNoOfGPTgt]              TINYINT         NULL,
    [FiveStarNoOfLSSTgt]             TINYINT         NULL,
    [FiveStarIndTgtDlvryVal]         NUMERIC (18, 2) NULL,
    [FiveStarProductivityTgt]        NUMERIC (18, 2) NULL,
    [TotOrderVal]                    NUMERIC (18, 2) NULL,
    [NoOfSKU]                        INT             NULL,
    [FiveStarNoOfGPAct]              TINYINT         NULL,
    [FiveStarNoOfLSSAct]             TINYINT         NULL,
    [FiveStarTotIndTgtDlvryVal]      NUMERIC (18, 2) NULL,
    [FiveStarAlrdyAchIndTgtDlvryVal] NUMERIC (18, 2) NULL,
    [NoOfStarsAch]                   TINYINT         NULL,
    [NoOfPendingVisits]              TINYINT         NULL,
    [TotInvVal]                      NUMERIC (18, 2) NULL,
    [FiveStarNoOfGPAchieved]         TINYINT         NULL,
    [FiveStarNoOfLSSAchieved]        TINYINT         NULL,
    [CallingSource]                  TINYINT         DEFAULT ((0)) NOT NULL,
    [flgCallConversionStatus]        TINYINT         NULL
);

