CREATE TABLE [dbo].[tblTCOrderDetail_History] (
    [OrderDetailID]        INT              NOT NULL,
    [OrderID]              INT              NOT NULL,
    [PrdNodeId]            INT              NOT NULL,
    [PrdNodeType]          INT              NOT NULL,
    [PrcBatchID]           INT              NOT NULL,
    [OrderQty]             INT              NOT NULL,
    [PriceTermId]          INT              NULL,
    [ProductRate]          DECIMAL (18, 10) NULL,
    [LineOrderVal]         NUMERIC (18, 2)  NOT NULL,
    [TotLineDiscVal]       NUMERIC (18, 2)  NULL,
    [LineOrderValWDisc]    NUMERIC (18, 2)  NULL,
    [TaxRefID]             INT              NULL,
    [TaxRate]              NUMERIC (18, 2)  NULL,
    [TotTaxValue]          NUMERIC (18, 2)  NULL,
    [NetLineOrderVal]      NUMERIC (18, 2)  NULL,
    [LoginIDIns]           INT              NOT NULL,
    [TimestampIns]         DATETIME         NOT NULL,
    [LoginIDUpd]           INT              NULL,
    [TimestampUpd]         DATETIME         NULL,
    [SampleQty]            INT              NULL,
    [SalesUnitId]          INT              NULL,
    [FreeQty]              INT              NULL,
    [strSchemeSource]      VARCHAR (500)    NULL,
    [flgRateChange]        BIT              NOT NULL,
    [strBatchPrice]        VARCHAR (1000)   NULL,
    [ProductRateBeforeTax] DECIMAL (18, 10) NULL,
    [flgQuotationApplied]  BIT              NOT NULL,
    [SalesQuoteDetId]      INT              NULL,
    [flgSBDGAP]            TINYINT          DEFAULT ((0)) NOT NULL,
    [flgFB]                TINYINT          DEFAULT ((0)) NOT NULL,
    [flgInitiative]        TINYINT          DEFAULT ((0)) NOT NULL,
    [SBDGroupId]           INT              DEFAULT ((0)) NOT NULL,
    [InvLevelDisc]         NUMERIC (18, 2)  DEFAULT ((0)) NOT NULL,
    [flgSBD]               TINYINT          DEFAULT ((0)) NOT NULL,
    [FBID]                 INT              DEFAULT ((0)) NOT NULL
);

