CREATE TABLE [dbo].[tblTCOrderMaster_Cancel] (
    [OrderID]                 INT             NOT NULL,
    [OrderCode]               VARCHAR (50)    NULL,
    [VisitID]                 INT             NULL,
    [OrderDate]               DATE            NOT NULL,
    [SalesPersonID]           INT             NOT NULL,
    [SalesPersonType]         TINYINT         NOT NULL,
    [RouteNodeId]             INT             NULL,
    [RouteNodeType]           INT             NULL,
    [StoreID]                 INT             NOT NULL,
    [TotalDeliveryBy]         DATE            NULL,
    [Remarks]                 VARCHAR (100)   NULL,
    [TotLineOrderVal]         NUMERIC (18, 2) NULL,
    [TotLineLevelDisc]        NUMERIC (18, 2) NULL,
    [TotOrderVal]             NUMERIC (18, 2) NOT NULL,
    [TotDiscVal]              NUMERIC (18, 2) NULL,
    [TotOrderValWDisc]        NUMERIC (18, 2) NULL,
    [TotTaxVal]               NUMERIC (18, 2) NULL,
    [NetOrderValue]           NUMERIC (18, 2) NOT NULL,
    [CustomerPONo]            VARCHAR (30)    NULL,
    [CustomerPODate]          DATE            NULL,
    [flgInvoiceOnDelivery]    TINYINT         NOT NULL,
    [flgCollectionOnDelivery] TINYINT         NOT NULL,
    [FreightRuleID]           TINYINT         NOT NULL,
    [CollectionRuleID]        TINYINT         NOT NULL,
    [DlvryRuleID]             TINYINT         NULL,
    [InvRuleID]               TINYINT         NULL,
    [InsRuleID]               TINYINT         NULL,
    [TaxRuleID]               TINYINT         NULL,
    [OrderStatusID]           TINYINT         NULL,
    [OrderSourceID]           TINYINT         NOT NULL,
    [flgOrderClosed]          TINYINT         NOT NULL,
    [LoginIDIns]              INT             NULL,
    [TimestampIns]            DATETIME        NULL,
    [LoginIDUpd]              INT             NULL,
    [TimestampUpd]            DATETIME        NULL,
    [FYID]                    INT             NULL,
    [OrderConfirmationDate]   SMALLDATETIME   NULL,
    [OrderCompletionDate]     SMALLDATETIME   NULL,
    [strSchemeBenefit]        VARCHAR (MAX)   NULL,
    [OrderInitTag]            VARCHAR (3)     NULL,
    [OrderSeqNo]              INT             NULL,
    [SalesNodeId]             INT             NULL,
    [SalesNodeType]           INT             NULL,
    [ActAddDisc]              NUMERIC (18, 2) NULL,
    [OrderLogId]              INT             NULL,
    [flgOffline]              TINYINT         NULL,
    [OrdPrcsId]               TINYINT         NOT NULL,
    [flgInvoicePrinted]       TINYINT         NOT NULL,
    [ReasonId]                INT             NOT NULL,
    [ReasonText]              VARCHAR (500)   NULL,
    [OrderPDAID]              VARCHAR (100)   NULL,
    [TotOtherCharges]         NUMERIC (18, 2) NOT NULL,
    [TeleCallingId]           INT             NULL,
    [DistNodeId]              INT             NOT NULL,
    [DistNodeType]            INT             NOT NULL,
    [CycleId]                 INT             NOT NULL,
    [flgSent]                 INT             NOT NULL
);

