CREATE TABLE [dbo].[tmpRawDataProductMaster] (
    [temp_Product Division]           NVARCHAR (500) NULL,
    [temp_Primary Category]           NVARCHAR (500) NULL,
    [temp_Standard Unit]              NVARCHAR (500) NULL,
    [Super Unit]                      NVARCHAR (500) NULL,
    [temp_Secondary Category]         NVARCHAR (500) NULL,
    [temp_Display Category]           NVARCHAR (500) NULL,
    [Product]                         NVARCHAR (500) NULL,
    [Variant]                         NVARCHAR (500) NULL,
    [PTR]                             NVARCHAR (500) NULL,
    [PTD]                             NVARCHAR (500) NULL,
    [Display MRP]                     NVARCHAR (500) NULL,
    [MRP]                             NVARCHAR (500) NULL,
    [Unit]                            NVARCHAR (500) NULL,
    [Alternate Category]              NVARCHAR (500) NULL,
    [Description]                     NVARCHAR (500) NULL,
    [Standard Unit Conversion Factor] NVARCHAR (500) NULL,
    [Super Unit Conversion Factor]    NVARCHAR (500) NULL,
    [Product Erp Id]                  NVARCHAR (500) NULL,
    [Schemes]                         NVARCHAR (500) NULL,
    [Display Order]                   NVARCHAR (500) NULL,
    [Is Promoted]                     NVARCHAR (500) NULL,
    [Packaging Type]                  NVARCHAR (500) NULL,
    [Minimum Batch Quantity]          NVARCHAR (500) NULL,
    [Pack Size]                       NVARCHAR (500) NULL,
    [Color Name]                      NVARCHAR (500) NULL,
    [RGB Values]                      NVARCHAR (500) NULL,
    [ImageId]                         NVARCHAR (500) NULL,
    [Product Weight in gm]            NVARCHAR (500) NULL,
    [Short Name]                      NVARCHAR (500) NULL,
    [HSN Code]                        NVARCHAR (500) NULL,
    [Shelf Life In Days]              NVARCHAR (500) NULL,
    [Barcode]                         NVARCHAR (500) NULL,
    [Net Weight]                      NVARCHAR (500) NULL,
    [Gross Weight]                    NVARCHAR (500) NULL,
    [PTRMT]                           NVARCHAR (500) NULL,
    [PTD Super]                       NVARCHAR (500) NULL,
    [PTD Sub]                         NVARCHAR (500) NULL,
    [Product_AttributeText1]          NVARCHAR (500) NULL,
    [Product_AttributeText2]          NVARCHAR (500) NULL,
    [Product_AttributeBoolean1]       NVARCHAR (500) NULL,
    [Product_AttributeBoolean2]       NVARCHAR (500) NULL,
    [Product_AttributeNumber1]        NVARCHAR (500) NULL,
    [Product_AttributeNumber2]        NVARCHAR (500) NULL,
    [Product_AttributeDate1]          NVARCHAR (500) NULL,
    [Product_AttributeDate2]          NVARCHAR (500) NULL,
    [GUID]                            NVARCHAR (500) NULL,
    [HASHKEY]                         NVARCHAR (500) NULL
);

