CREATE TABLE [dbo].[tmpSalesHierarchyImport] (
    [Region]              VARCHAR (200) NULL,
    [RSMEmpCode]          VARCHAR (20)  NULL,
    [RSMName]             VARCHAR (200) NULL,
    [RSMEMailID]          VARCHAR (200) NULL,
    [RSMContactNo]        BIGINT        NULL,
    [StateHead]           VARCHAR (200) NULL,
    [StateHeadEmpCode]    VARCHAR (20)  NULL,
    [StateHeadName]       VARCHAR (200) NULL,
    [StateHeadEMailID]    VARCHAR (200) NULL,
    [StateHeadContactNo]  BIGINT        NULL,
    [ASMArea]             VARCHAR (200) NULL,
    [ASMEmpCode]          VARCHAR (20)  NULL,
    [ASMName]             VARCHAR (200) NULL,
    [ASMEMailID]          VARCHAR (200) NULL,
    [ASMContactNo]        BIGINT        NULL,
    [SOArea]              VARCHAR (200) NULL,
    [TSIEmpCode]          VARCHAR (20)  NULL,
    [TSIName]             VARCHAR (200) NULL,
    [SOEMailID]           VARCHAR (200) NULL,
    [SOContactNo]         BIGINT        NULL,
    [CoverageArea]        VARCHAR (200) NULL,
    [DSMName]             VARCHAR (200) NULL,
    [DSMEmpCode]          VARCHAR (20)  NULL,
    [DSMEMailID]          VARCHAR (200) NULL,
    [DSMContactNo]        BIGINT        NULL,
    [RouteCode]           VARCHAR (20)  NULL,
    [RouteName]           VARCHAR (200) NULL,
    [RegionID]            INT           NULL,
    [RegionHierID]        INT           NULL,
    [StateHeadAreaID]     INT           NULL,
    [StateHeadAreaHierID] INT           NULL,
    [ASMAreaID]           INT           NULL,
    [ASMHierID]           INT           NULL,
    [SOAreaID]            INT           NULL,
    [SOAreaHierID]        INT           NULL,
    [CoverageAreaID]      INT           NULL,
    [CoverageAreaHierID]  INT           NULL,
    [RSMID]               INT           NULL,
    [STATEHEADID]         INT           NULL,
    [ASMID]               INT           NULL,
    [TSIID]               INT           NULL,
    [DSMID]               INT           NULL,
    [RouteNodeID]         INT           NULL,
    [RouteHierID]         INT           NULL,
    [DHNodeID]            INT           NULL,
    [DHNodeType]          SMALLINT      NULL,
    [DistributorCode]     VARCHAR (50)  NULL,
    [Distributor]         VARCHAR (200) NULL,
    [State]               VARCHAR (200) NULL,
    [StateID]             INT           NULL
);

